import { ReactNode } from "react";

import type { Metadata } from "next";

import clsx from "clsx";

import "@styles/globals.css";

import { ThemeProvider } from "@libs/providers";
import { poppins, firaCode } from "@libs/fonts";

// import { Toaster } from "@components/elements/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const bodyClasses = clsx(
    "antialiased font-sans text-base leading-normal font-normal",
    "overflow-x-hidden text-foreground bg-background"
  );

  const theme = "light";

  return (
    <html lang="en" suppressHydrationWarning className={clsx(poppins.variable, firaCode.variable)}>
      <body className={bodyClasses}>
        <ThemeProvider attribute="class" defaultTheme={theme} enableSystem>
          {children}
          {/* <Toaster /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
